Code review pull request for the animation recorder.
froglet-studio/Cosmic-Shore pull request #25
Opened 2024-06-26 00:13 UTC by eje211

Hello and welcome to our first code review!

The code you will be reviewing is mine. Everyone should take the time to read the code and see if it (the code) makes sense to them. This is the criterion you should be looking for: if later on you find the code confusing, it is your fault and your fault alone because before it was merged, you actually approved it. So make sure that everything makes sense to you before you approve! And please, stick to this until you approve.

The code review is not about whether the new feature works. It should already be working when the review starts. In other words, if you find a problem with how it works, that's great! And a comment about what you found. But if the utility works on your computer, it's not enough. You need to actually read the code and see if it makes sense to you.

Comments are very important. Do the comments seem useful? It is not enough that they are accurate. They need to be useful. When you are looking for a method, the comments should tell you pretty much everything you need (within reason) in order to understand it, without the act of figuring out the code having to be a big effort.

Anyone who may have to go through this code and most people who will have to use the utility should approve this before it is merged. I may not have included the right people. Hopefully Garrett can fix that.

The way the utility works should be simple to understand. Leave comments if it isn't. It is called by opening the recorder window by using the menu item "Windows/Animation Recorder" If you think that the menu item should be elsewhere, leave a comment to that effect.

The utility should look more or less like this:

![image](https://github.com/froglet-studio/Cosmic-Shore/assets/1558357/ffa75bab-9d7b-4004-89f5-c6952a25e306)

There may be differences on different setups.

All of its fields need to be filled before it can record. This is what Unity calls a "regular window." That means it can be docked like most of the other windows. (If you think it should be the type of simpler window that can't be docked, leave a comment to that effect.) It needs an animation manager with a timeline, which is any game object that has a Playable Director component. It **needs** a game object in the scene that's called "Animation Manager". If that's a problem, leave a comment to that effect. You can add any game object to the list of "objects to track" and these objects will be tracked during the recording.

If all the required data is filled out, once the editor goes to play mode, it should be possible to start recording. At that moment, you start and stop a recording with the corresponding buttons. Nothing will be added to the timeline at that moment. When you return to "edit mode," the timeline will be updated with your new animations. Unity does not update the interface at that moment, so if the animation manager is selected at that moment, just select another game object in the hierarchy and select the animation manager again.

The idea here is not to have someone say in a couple of weeks or in a couple of months, "Hey! What does the animation recorder to A like this, and not like that? And why can't it do B?" The time to bring this up is now.

It will not be perfect even after this code review, but try to make as many relevant comments as you think it's useful. Yes, you will be able to make them later, but the moment to talk about them is now if you can.

Please take the time to do this. It's not fun, I know. But it helps prevent a lot of problems downstream.

It should not be possible to merge until everyone has approved the code.

2024-06-26 00:43 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        [MenuItem("Window/Animation Recorder")]
The menu item should not be in "window" but under the "Froglet" menu. Consider changing that.

2024-06-26 00:46 UTC, gradies approved these changes

2024-06-26 01:05 UTC, gradies requested changes
some spelling changes

2024-06-26 01:05 UTC, gradies commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// When recording, time until the next snapshot. When this timer reacher 0, the utility
reacher -> reaches

2024-06-26 01:05 UTC, gradies commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// window when uctivated.
uctivated -> activated

2024-06-26 01:05 UTC, gradies commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// This update method words as a replacement for Coroutines, which are not available
words -> works

2024-06-26 01:05 UTC, gradies commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// Ren when the editor returns to edit mode. Adds new items to the timeline based
Ren -> run

2024-06-28 21:16 UTC, KidIgarus commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +                AssetDatabase.CreateAsset(animationClip, $"{currentAssetsPath}/{currentGameObject.name}.asset");
Is there any concern about file overwriting? Consider making the root folder of the automatically created assets a subfolder of Assets (rather than the Assets folder itself). Consider checking for an existing file with the provided path and name combination and handling collisions (e.g appending a number or a timestamp).

2024-06-28 21:16 UTC, KidIgarus commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +            float recordingDelay = 1; // serializedObject.FindProperty(RecordingDelay).floatValue;
Looks like this should be uncommented to be consistent with the behavior in TakeSnapshot

2024-06-28 21:16 UTC, KidIgarus commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
Minor typos in the comments: replace all instances of refrence(s) with reference(s)

2024-06-28 22:22 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
I tried very hard never to use a `foreach` loop. I'd heard that they were never to be used in games because they can cause slowness and garbage collection issues: https://gamedev.stackexchange.com/questions/149914/why-is-the-for-loop-more-efficient-than-the-for-each-loop-in-unity (There is also a belief that games should never use garbage collection anyway, but that's not an option in Unity.) I'd much rather use `foreach` loops than enumerators. If the consensus is that I should, I'll gladly change them all.

2024-06-28 22:23 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +            GUILayout.Space(10);
I hadn't noticed that! This block got changed so many times that it must have escaped me. Thanks!

2024-06-28 22:25 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        private static readonly string ManagerName = "Animation Manager";
I always have to rename everything, so I lose the ability to keep the names coherent when I'm doing my last pass. Thank you so much for this!

2024-06-28 22:27 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +                isRecording = false;
An exception may be risen at any moment for any reason (more or less). I _really_ don't want to risk an infinite loop, so I set the flag variable before I do anything else. If there is a consensus that this fear is excessive, I'll change it.

2024-06-28 22:31 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
I was absolutely sure that the default accessibility level was `protected`, but I was wrong: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers

In general, for that sort of reason (the ambiguity of it all), an accessibility level should be specified every time. It's a lot like operator precedence: it's better to add parentheses than to rely on them. They may be counter-intuitive to some people. In short: yet, it was a mistake. I'll fix it.

2024-06-28 22:35 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +                AssetDatabase.CreateAsset(animationClip, $"{currentAssetsPath}/{currentGameObject.name}.asset");
This is a mistake and most likely a remnant of some old attempt. The path should include `assetsPath` from the data holder.

2024-06-28 22:36 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +            float recordingDelay = 1; // serializedObject.FindProperty(RecordingDelay).floatValue;
It should not be there, exactly. I just didn't notice it. No code that's commented out should be merged.

2024-06-28 22:37 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
I make that knid of typo soemtmies. My bda. I'll fxi it. ☺

2024-06-28 22:39 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// When recording, time until the next snapshot. When this timer reacher 0, the utility
I common typo of mine: r and s switched. (I use a weird keyboard layout where they are next to each other.) Another is "it" and "I" switched as well, which can lead to awkward social media comments...

2024-06-28 22:40 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        /// window when uctivated.
Muybe thut's whut I meunt! Uh... No. ~~Thunks~~ Thanks.

2024-07-02 16:57 UTC, KidIgarus commented on Assets/_Scripts/Utility/Recording/dataHolder.cs
> +    public class DataHolder : MonoBehaviour
In this case, the RecorderWindow.cs class is looking for a DataHolder component on the "Animation Manager" game object in the active scene. In order for a class to be added to a game object as a component, it needs to inherit from Monobehavior (regardless of whether it uses the lifecycle events).

That said, it maybe better to use a Scriptable Object in this case. Using the compiler directive "if UnityEditor" may cause serialization issues when building for stand alone. The RecorderWindow could then be an interface to start a recording, and modify the scriptable object that saves the recording settings for the loaded scene.

```
using UnityEngine;

public class DataHolder : ScriptableObject
{
    public string sceneName;  // Tag to associate with a scene
    // ... other properties
    public Animator[] gameObjectsToTrack;
}
```

2024-07-03 01:13 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/dataHolder.cs
> +    public class DataHolder : MonoBehaviour
The Unity UI requires a property object specifically. I've only been able to use one with a component. If you find out how to use a property object without a component, let me know.

2024-07-08 23:59 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
@KidIgarus Please let me know if you still think I should use `foreach` loops. I'm sort of on the fence on this.

2024-07-09 00:06 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +            GUILayout.Space(10);
@KidIgarus So, I changed it. But there was another problem. (I really must have been out of it last week if I didn't notice it.)

The main problem is that, in this context, `10` is magic number. (In the first meaning on [the Wikipedia page about magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants) .) Magic numbers are the [Wrong Thing](https://foldoc.org/Wrong+Thing).

2024-07-09 00:12 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +        private DataHolder Holder
That was the cause of a _very_ annoying infinite loop. Fixed.

2024-07-09 00:33 UTC, eje211 commented on Assets/_Scripts/Utility/Recording/RecorderWindow.cs
> +                AssetDatabase.CreateAsset(animationClip, $"{currentAssetsPath}/{currentGameObject.name}.asset");
Actually, the default path includes `Assets`. If the user wants to put the saved files outside of the assets folder, I'll allow it for now.

2024-07-20 20:58 UTC, KidIgarus commented on Assets/_Scripts/Utility/Recording/AnimationRecorderData.cs
Looks good. Only Comment is to make sure the Class name and File name match. Unity does some kind of inference using the file name and will say that it can't find the type DataHolder since it's name doesn't match the file name.

2024-08-02 23:40 UTC, merged